### ISSUE TITLE
能够在课程介绍中添加教科书的说明吗

### ISSUE THREAD

**Issue by houkensjtu** [PKUanonym/REKCARC-TSC-UHT#1]
RT，可能上传教科书是导致了上次repo侵权问题，不过还是希望可以至少注明一下使用的是什么版本的哪本教科书。
感谢你们无私的劳动！

**Comment by PKUanonym** [comment]
一般情况下，或者是清华大学自己出版的教材，或者是国外的著名到搜索课程名就可以搜到翻译版的书，或者是用PPT

**Comment by houkensjtu** [comment]
我的意思可能没有说清楚，我是说在每门课程的的文件夹中的Readme.md里注明一下使用的教科书title。
当然这只是一个我个人的期望，谢谢！

**Comment by gongbo2018** [comment]
我也觉得@houkensjtu 同学说的挺好，
只要注明教材名称 和 版本， 书籍啥的  想学的同学自己肯定可以搞定。

**Comment by zouyonghao** [comment]
支持

**Comment by amesy** [comment]
强烈支持！ 
感谢你们无私的劳动！

**Comment by DreaMer963** [comment]
如果有PPT的话可以上传一下吗？
感谢

**Comment by lizhiwei92** [comment]
+1；能否有教材相关资料？

**Comment by PKUanonym** [comment]
非常感谢你们的建议！
1、如果有时间的话，会在下一次大型更新时补充一些已知的教材名称和版本，但可能不全；
2、PPT是老师的劳动成果，在未取得老师许可之前不允许上传。

**Comment by limjcst** [comment]
- 两本《高等微积分教程》的作者之一是章纪民老师，[参考书目.md](/PKUanonym/REKCARC-TSC-UHT/blob/master/参考书目.md)中打成了“张”。
- 数据结构课程有一个邓俊辉老师的[链接](https://dsa.cs.tsinghua.edu.cn/~deng/ds/dsacpp/index.htm)。
- 计算机网络专题训练在2017年使用的实验指导书是《计算机网络原理实验教程(第二版)》，但只做了其中ipv6转发实验，另两个实验是在实验室的NetRiver上做的。

**Comment by houkensjtu** [comment]
感谢你们更新了书目！
