### ISSUE TITLE
高中生

### ISSUE THREAD

**Issue by NightKillerMonster** [PKUanonym/REKCARC-TSC-UHT#116]
我是个高中生，想来白嫖一下清华的计算机和物理和数学，因为以后想要走竞赛。不知道各位清华的学长学姐能不能帮帮我，到时到清华来找你们，总之谢谢了！

**Comment by zhaochenyang20** [comment]
高中生太卷了，别来了吓我

**Comment by tommyjiang** [comment]
哈哈哈，买的北大物理书亮了。
