### ISSUE TITLE
清华大学人工智能班

### ISSUE THREAD

**Issue by ghost** [PKUanonym/REKCARC-TSC-UHT#118]
请问下，这个课程和清华人工智能班（智班）学的差不多嘛？非科班出身，想学习一下。更想偏向AI而不是CS。有没有大佬能分享下清华人工智能的攻略。[期待！]

**Comment by wang-hr20** [comment]
> 请问下，这个课程和清华人工智能班（智班）学的差不多嘛？非科班出身，想学习一下。更想偏向AI而不是CS。有没有大佬能分享下清华人工智能的攻略。[期待！]

智班的课都是叉院单开的，和贵系区别很大

**Comment by xiaomeng2345** [comment]
您好，我是孟贇祥，您的邮件我已经收到。我会尽快处理麻烦您了。
