### ISSUE TITLE
为什么是北大的校徽？

### ISSUE THREAD

**Issue by zhixuanli** [PKUanonym/REKCARC-TSC-UHT#2]
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by plazum** [comment]
抬头看看owner……咦他怎么只有这一个repo

**Comment by houkensjtu** [comment]
Top名校之间互相较劲的一个喜闻乐见的方式把。。X盆子都自主戴到对方的头上这样。
当然这些都只是课间娱乐的joke，不用太当真。。

**Comment by wphp** [comment]
为什么用我们的校徽

**Comment by Adonishl** [comment]
用户名还是北大匿名……

**Comment by Billyyanyz** [comment]
太真实了）
