### ISSUE TITLE
兄弟们，问下徐明星老师的《程序设计基础（第4版）》配套的视频有嘛？

### ISSUE THREAD

**Issue by MoeRookie** [PKUanonym/REKCARC-TSC-UHT#30]

**Comment by MoeRookie** [comment]
我好像从学堂在线找到了这位老师的教程 ，但提示"认证已截止"了是什么鬼？我该如何才能使用到这个教程？

**Comment by PatrickFFung** [comment]
学堂在线有, "认证已截止"可以重新搜索加入新的学期课程, 过期的就不能看了

**Comment by jack-ma-hub** [comment]
不能全部开放出来吗？

**Comment by LittleOrange62** [comment]
您的邮件我已收到，谢谢！ 工作邮件我会在工作日上午九点接收并处理问题，三个工作日内必将回复您！谢谢！

**Comment by xiaomeng2345** [comment]
您好，我是孟贇祥，您的邮件我已经收到。我会尽快处理麻烦您了。
