### ISSUE TITLE
大二上/电子学基础/第二次作业/1-34题 参考答案错误

### ISSUE THREAD

**Issue by will7101** [PKUanonym/REKCARC-TSC-UHT#38]
![image](https://user-images.githubusercontent.com/20700650/65831860-55bd2b80-e2f0-11e9-910a-ac58d89a55b9.png)

最右侧应该是受控电压源而不是电流源。

> 评语：1-34 2I是受控电压源，输出的是电压而不是电流。本题可以不需要求出I的大小而直接验证功率守恒。

（其实我也不会）

**Comment by Trinkle23897** [comment]
可以加到对应的readme里面，放issue没啥用没人看

**Comment by 1610983794** [comment]
计算机系祖传错题
