### ISSUE TITLE
关于一些文件的所有权

### ISSUE THREAD

**Issue by limjcst** [PKUanonym/REKCARC-TSC-UHT#53]
网络学堂中的课程文件、试题（及其照片）并不属于本项目贡献者所有，比如模式识别课程作业提供的一些论文甚至不属于授课教师。

（无意要求删除这些文件，但这些文件构成本项目的风险

**Comment by zhaochenyang20** [comment]
我们已经注意到了这些风险，并且相应删除了这些敏感资料，感谢支持__
