### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by GitHub-huyuan** [PKUanonym/REKCARC-TSC-UHT#7]

**Comment by GitHub-huyuan** [comment]
这个会更新吗？能把所有需要动手做的上机实验放在一个文件夹里吗

**Comment by PKUanonym** [comment]
会更新。
提这个需求的原因是？

**Comment by GitHub-huyuan** [comment]
就是想动手系统地都做一遍实验

**Comment by Trinkle23897** [comment]
You can refer to https://github.com/Trinkle23897/Personal-Homework

**Comment by retbone** [comment]
他仅仅想考研去清华而已，没有thinpad实验板，fuck！！！
