### ISSUE TITLE
复变函数ygw18-19期末答案疑似有误

### ISSUE THREAD

**Issue by panda2134** [PKUanonym/REKCARC-TSC-UHT#92]
https://github.com/PKUanonym/REKCARC-TSC-UHT/tree/master/%E5%A4%A7%E4%BA%8C%E4%B8%8A/%E5%A4%8D%E5%8F%98%E5%87%BD%E6%95%B0%E5%BC%95%E8%AE%BA/exam/%E5%A7%9A%E5%9B%BD%E6%AD%A6/%E5%A4%8D%E5%8F%98%202019.1%20%E5%A7%9A%E5%9B%BD%E6%AD%A6%20%E9%A2%98%E7%9B%AE%E5%8F%8A%E7%AD%94%E6%A1%88

填空第八题答案第一个等号错了，多了个负号

**Comment by panda2134** [comment]
![图片](https://user-images.githubusercontent.com/7239200/103436282-c3bf7380-4c54-11eb-8088-2f4612d25253.png)

**Comment by Trinkle23897** [comment]
你加个readme来个PR改下？

**Comment by panda2134** [comment]
https://github.com/PKUanonym/REKCARC-TSC-UHT/pull/93
